# Generated by Django 2.1.5 on 2020-09-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_player_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('GK', 'Goalkeeper'), ('CB', 'Centerlane'), ('SW', 'Sweeper'), ('LFB', 'Left fullback'), ('RFB', 'Right fullback'), ('WB', 'Wingback')], max_length=3),
        ),
    ]
