# Generated by Django 2.1.5 on 2020-09-15 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20200915_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='build',
            new_name='age',
        ),
    ]
