# Generated by Django 2.1.5 on 2020-09-18 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_auto_20200916_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='coach',
            new_name='lead',
        ),
    ]
