# Generated by Django 2.1.5 on 2020-09-29 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_auto_20200918_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('T1', 'Standby'), ('T2', 'Research'), ('T3', 'Field')], max_length=3),
        ),
    ]
