# Generated by Django 2.1.5 on 2020-09-29 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_auto_20200929_0904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='age',
            new_name='months_active',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='position',
            new_name='task_assigned',
        ),
    ]
