# Generated by Django 2.1.5 on 2020-09-29 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_auto_20200929_0910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='months_active',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='task_assigned',
            new_name='position',
        ),
    ]
