# Generated by Django 2.1.5 on 2020-09-29 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0012_auto_20200929_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='age',
            new_name='months_active',
        ),
    ]
