# Generated by Django 2.1.5 on 2020-09-15 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20200915_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='age',
            new_name='build',
        ),
    ]
