# Generated by Django 2.1.5 on 2020-09-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20200916_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('GK', 'Goalkeeper'), ('CB', 'Center fullback'), ('SW', 'Sweeper'), ('LFB', 'Left fullback'), ('RFB', 'Right fullback'), ('WB', 'Wingback'), ('LM', 'Left midfield'), ('RM', 'Right midfield'), ('DM', 'Defensive midfield'), ('CM', 'Center midfield'), ('WM', 'Wide midfield'), ('CF', 'Center forward'), ('AM', 'Attacking midfield'), ('S', 'Striker'), ('SS', 'Second striker'), ('LW', 'Left winger'), ('RW', 'Right winger')], max_length=3),
        ),
    ]
