# Generated by Django 2.1.5 on 2020-09-18 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_auto_20200918_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='practice_location',
            new_name='field_location',
        ),
    ]
