# Generated by Django 2.1.5 on 2020-09-29 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_auto_20200929_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('months_active', models.PositiveIntegerField()),
                ('activity', models.CharField(choices=[('T1', 'Standby'), ('T2', 'Research'), ('T3', 'Field')], max_length=3)),
                ('team', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='status', to='teams.Team')),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
