# Generated by Django 2.1.5 on 2020-09-29 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0014_auto_20200929_0919'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='Status_detail',
        ),
    ]
