# Generated by Django 3.1.2 on 2020-10-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('region', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'provinces',
            },
        ),
    ]
