# Generated by Django 3.1.2 on 2020-10-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='region',
            field=models.CharField(max_length=20),
        ),
    ]
