# Generated by Django 3.1.2 on 2020-10-30 07:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20201030_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='products',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
