# Generated by Django 3.1.2 on 2020-10-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_province_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='area',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
