# Generated by Django 3.1.2 on 2020-10-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_province_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='area',
            field=models.IntegerField(default=0),
        ),
    ]
