# Generated by Django 3.1.2 on 2020-10-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20201030_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='area',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
