# Generated by Django 3.1.2 on 2020-10-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_auto_20201030_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
