# Generated by Django 2.1.5 on 2020-09-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('HP', 'High Priority'), ('NP', 'Normal Priority'), ('LP', 'Low Priority'), ('SOS', 'Emergency'), ('RS', 'Reschedule')], max_length=3),
        ),
    ]
