# Generated by Django 2.1.5 on 2020-09-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200924_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('HP', 'High Priority'), ('NP', 'Normal Priority'), ('LP', 'Low Priority'), ('SOS', 'Emergency'), ('RS', 'Reschedule')], default='NP', max_length=3),
        ),
    ]
