# Generated by Django 2.1.5 on 2020-09-24 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0002_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(default='', max_length=255)),
                ('priority', models.CharField(choices=[('HP', 'High Priority'), ('NP', 'Normal Priority'), ('LP', 'Low Priority'), ('SOS', 'Emergency'), ('RS', 'Reschedule')], default='NP', max_length=3)),
                ('start', models.TimeField(default=datetime.time(8, 0))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
