# Generated by Django 2.1.5 on 2020-09-24 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200924_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='start',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
    ]
