# Generated by Django 2.1.5 on 2020-09-24 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
