# Generated by Django 2.1.5 on 2020-12-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchlocations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='name',
        ),
        migrations.AddField(
            model_name='province',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='City/Municipality'),
        ),
        migrations.AlterField(
            model_name='province',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='products',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='region',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
