# Generated by Django 2.1.5 on 2021-01-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchlocations', '0002_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
            ],
            options={
                'verbose_name_plural': 'testlocations',
            },
        ),
    ]
